plugins {
    id 'java'
    id 'application'
}

group 'org.shrvn'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = "https://dl.bintray.com/algs4/maven/"
    }
}

dependencies {
    implementation 'edu.princeton.cs:algs4:1.0.4'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
}

test {
    useJUnitPlatform()
}